In [2]:
%load_ext autoreload

%autoreload 2


In [11]:
import md1k
import analytical as anal
import pandas as pd
import numpy as np
from numpy.linalg import matrix_power
pd.set_option('display.max_rows', 999)

In [37]:
def metrics(sim_data, N, lamda, mu):
    simulated = {
        'customers' : md1k.customers_mean(sim_data),
        'wait_time' : md1k.mean_wait(sim_data),
        'utilization' : md1k.utilization(sim_data)
    }
    analytical = {
        'customers' : anal.mean_customers(N, lamda, mu),
        'wait_time' : anal.mean_wait(N, lamda, mu)
    }
    print(f"""
Fila M/D/1/{N} 
    lambda = {lamda}
    D = {1/mu}
    Média de Consumidores
        Resultado simulado:
            Média: {simulated['customers']['mean']}
            Intervalo de Confiança: {simulated['customers']['ci']}
        Resultado Analítico: {analytical['customers']}
    Tempo Médio
        Resultado simulado:
            Média : {simulated['wait_time']['mean']}
            Intervalo de Confiança: {simulated['wait_time']['ci']}
        Resultado Analítico: {analytical['wait_time']}
    Utilização:
        Resultado Simulado:
            Média : {simulated['utilization']['mean']}
            Intervalo de Confiança: {simulated['utilization']['ci']}
""")

In [44]:
lamda = 3
mu = 1
N = 3
sim = md1k.md1k_simulation(lamda,mu, N)
metrics(sim, N, lamda, mu)



Fila M/D/1/3 
    lambda = 3
    D = 1.0
    Média de Consumidores
        Resultado simulado:
            Média: 2.6429434787849733
            Intervalo de Confiança: (2.6266984147478976, 2.659188542822049)
        Resultado Analítico: 2.6465289952952404
    Tempo Médio
        Resultado simulado:
            Média : 2.6332141943078073
            Intervalo de Confiança: (2.6195154432333436, 2.646912945382271)
        Resultado Analítico: 1.6490996475105941
    Utilização:
        Resultado Simulado:
            Média : 0.4990563587630814
            Intervalo de Confiança: (0.49860421347977507, 0.49950850404638775)



In [45]:
embedded_chain = anal.embedded_chain(N, lamda, mu)
embedded_chain

array([[0.04978707, 0.14936121, 0.80085173],
       [0.04978707, 0.14936121, 0.80085173],
       [0.        , 0.04978707, 0.95021293]])

In [46]:
stationary_distribution = matrix_power(embedded_chain, 1000)
stationary_distribution

array([[0.00291399, 0.05561505, 0.94147096],
       [0.00291399, 0.05561505, 0.94147096],
       [0.00291399, 0.05561505, 0.94147096]])

In [47]:
lamda = 50
mu = 10
sim = md1k.md1k_simulation(lamda,mu,3)
metrics(sim, N = N, lamda = lamda, mu = mu)


Fila M/D/1/3 
    lambda = 50
    D = 0.1
    Média de Consumidores
        Resultado simulado:
            Média: 2.805978346183268
            Intervalo de Confiança: (2.7915299064997297, 2.820426785866806)
        Resultado Analítico: 2.7985979237654686
    Tempo Médio
        Resultado simulado:
            Média : 0.2782675867945711
            Intervalo de Confiança: (0.2771960607505081, 0.27933911283863405)
        Resultado Analítico: 0.17986242209401493
    Utilização:
        Resultado Simulado:
            Média : 0.049804731872165144
            Intervalo de Confiança: (0.04976668098924459, 0.0498427827550857)



In [48]:
embedded_chain = anal.embedded_chain(N, lamda, mu)
embedded_chain

array([[0.00673795, 0.03368973, 0.95957232],
       [0.00673795, 0.03368973, 0.95957232],
       [0.        , 0.00673795, 0.99326205]])

In [49]:
stationary_distribution = matrix_power(embedded_chain, 1000)
stationary_distribution.round(4)

array([[0.    , 0.0069, 0.993 ],
       [0.    , 0.0069, 0.993 ],
       [0.    , 0.0069, 0.993 ]])